######################################################################
#
# File name : tb_hdb3_wave.do
# Created on: Tue Jun 16 13:40:41 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
