######################################################################
#
# File name : tb_hdb3_compile.do
# Created on: Tue Jun 16 15:05:38 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
F:\\Modelsim\\win64\\vlib modelsim_lib/work
F:\\Modelsim\\win64\\vlib modelsim_lib/msim

F:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

F:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

F:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../HDB3_sim.srcs/sources_1/new/hdb3_decoder.v" \
"../../../../HDB3_sim.srcs/sources_1/new/hdb3_encoder.v" \
"../../../../HDB3_sim.srcs/sources_1/new/hdb3_top.v" \
"../../../../HDB3_sim.srcs/sim_1/new/tb_hdb3.v" \


# compile glbl module
F:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

