######################################################################
#
# File name : tb_hdb3_simulate.do
# Created on: Tue Jun 16 15:05:40 +0800 2026
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_hdb3 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_hdb3_wave.do}

view wave
view structure
view signals

do {tb_hdb3.udo}

run 1000ns
